# docker-compose version
version: "3.3"

# network
networks:
  data:
  management:

# computes
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ibm
      MONGO_INITDB_ROOT_PASSWORD: dao
      APP_USERNAME: fengxia
      APP_PASSWORD: natalie
    volumes:
      - ./backend/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8113:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ibm
      ME_CONFIG_MONGODB_ADMINPASSWORD: dao
      ME_CONFIG_MONGODB_URL: mongodb://ibm:dao@mongo:27017/
    depends_on:
      - mongo
    networks:
      - data
      - management

  backend:
    image: backend_ibm
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    environment:
      APP_USERNAME: fengxia
      APP_PASSWORD: natalie
    volumes:
      - ./backend:/code
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/code/data:ro
    ports:
      - "8111:80"
    networks:
      - data
      - management
    command: node server
    depends_on:
      - mongo

  frontend:
    image: frontend_ibm
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/code
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8112:80"
    command: [nginx-debug, "-g", "daemon off;"]
    depends_on:
      - backend
    networks:
      - management
